### ISSUE TITLE
Some issue in Aes128.cpp

### ISSUE THREAD

**Issue by xiaoxiaozhu5** [Anthony-Mai/TinyTls#2]
In https://github.com/Anthony-Mai/TinyTls/blob/master/src/aes/aes128.cpp#L162
variable j will increase to 8, this lead to j + j equals to 16. but the array br has only 16 elements. This will cause overflow. However in linux this fine, but in windows building with MSVC, this cause problem, Aes encryption and decryption will fail.
I don't know if my understanding is correct, if it is wrong, I hope you can correct me, thank you

**Comment by Anthony-Mai** [comment]
Sorry I did not see your comment early.

You are right there seems to be a bug. Please note in the loop, for (j = 1; j < 16; j+=j), j is doubled each time, not incremented by 1. This line should be executed for each iteration except for the last one:
(p[br[j + j]] = p[br[j]]).shiftR();
To fix the bug, just add a condition that (j+j<16):
 if (j+j<16) (p[br[j + j]] = p[br[j]]).shiftR();
Thanks for pointing that out. It was not catched by the unit test. I will fix it.
